export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
};

export const bankConstants = {
  GET_BANK_BRANCHES_REQUEST: "GET_BANK_BRANCHES_REQUEST",
  GET_BANK_BRANCHES_FAILURE: "GET_BANK_BRANCHES_FAILURE",
  GET_BANK_BRANCHES_SUCCESS: "GET_BANK_BRANCHES_SUCCESS",
  ADD_TO_FAV_LIST_SUCCESS: "ADD_TO_FAV_LIST_SUCCESS",
};
